# Generated by Django 4.2.1 on 2024-03-25 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='queryNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('query_creator_name', models.CharField(max_length=100)),
                ('query_name', models.CharField(max_length=100)),
                ('owner_PhNo', models.CharField(blank=True, max_length=100)),
                ('Owner_reg', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll', models.CharField(max_length=100, unique=True)),
                ('call', models.CharField(default='1234567890', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AddQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('registration_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('checkbox_field', models.BooleanField(default=False)),
                ('radio_field', models.CharField(choices=[('PhonePay to Cash', 'PhonePay to Cash'), ('Cash to Phonepay', 'Cash to Phonepay')], max_length=100)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
